version: "3.9"
services:
    nginx:
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        container_name: nginx-container
        ports:
            - "443:443"
        volumes:
            - ./requirements/nginx:/nginx_tmp
            - ./requirements/wordpress/srcs/wordpress:/var/www/wordpress
    wordpress:
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        container_name: wordpress-container
        volumes:
            - ./requirements/wordpress/srcs/wordpress:/var/www/wordpress
    mariadb:
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        container_name: mariadb-container
        volumes:
            - db_data:/var/lib/mysql
    ftp:
        build:
            context: ./requirements/ftp
            dockerfile: Dockerfile
        container_name: ftp-container
        ports:
            - "20:20"
            - "21:21"
            - "21000:21000"
        volumes:
            - ./requirements/wordpress/srcs/wordpress:/home/ndreadno/
    adminer:
        build:
            context: ./requirements/adminer
            dockerfile: Dockerfile
        container_name: adminer-container
    redis:
        build: 
            context: ./requirements/redis
            dockerfile: Dockerfile
        container_name: redis-container
    influxdb:
        build:
            context: ./requirements/influxdb
            dockerfile: Dockerfile
        container_name: influxdb-container
    grafana:
        build:
            context: ./requirements/grafana
            dockerfile: Dockerfile
        container_name: grafana-container
        ports:
            - "3000:3000"
    telegraf:
        build:
            context: ./requirements/telegraf
            dockerfile: Dockerfile
        container_name: telegraf-container
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    
volumes:
    db_data: 
        # external:
        #     name: /Users/ndreadno/inception/srcs/requirements/mariadb/srcs/
